# Generated by Django 3.1.3 on 2020-12-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodannouncement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
