# Generated by Django 3.1.3 on 2020-12-15 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bloodannouncement', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, verbose_name='City'),
            preserve_default=False,
        ),
    ]
