# Generated by Django 3.1.3 on 2020-12-15 17:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bloodannouncement', '0004_user_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('expiretion_time', models.DateField()),
                ('created_date', models.DateField(default=datetime.datetime(2020, 12, 15, 17, 5, 40, 607331, tzinfo=utc))),
                ('bload_group', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=11)),
                ('hospital_address', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
