# Generated by Django 3.1.3 on 2020-12-15 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bloodannouncement', '0007_auto_20201215_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 17, 47, 10, 247030, tzinfo=utc)),
        ),
    ]
