# Generated by Django 3.1.3 on 2020-12-16 23:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bloodannouncement', '0013_announcement_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 23, 9, 31, 44932, tzinfo=utc)),
        ),
    ]
